apiVersion: v1
name: platform
home: https://jfrog.com/platform/
version: 0.0.1
appVersion: 7.3.2
description: JFrog Unified Platform
sources:
- https://github.com/jfrog/charts
keywords:
- artifactory
- jfrog
- container
- registry
- devops
maintainers:
- email: amithk@jfrog.com
  name: amithins
- email: daniele@jfrog.com
  name: danielezer
- email: eldada@jfrog.com
  name: eldada
- email: ramc@jfrog.com
  name: chukka
- email: rimasm@jfrog.com
  name: rimusz
icon: https://raw.githubusercontent.com/jfrog/charts/master/stable/artifactory-jcr/logo/jcr-logo.png
