dependencies:
  - name: artifactory
    version: 9.3.0
    repository: https://charts.jfrog.io/
  - name: xray
    version: 3.1.0
    repository: https://charts.jfrog.io/
  # - name: distribution
  #   version: 5.1.0
  #   repository: https://charts.jfrog.io/
  - name: mission-control
    version: 3.1.0
    repository: https://charts.jfrog.io/
  - name: pipelines
    version: 1.0.36
    repository: https://charts.jfrog.io/
