dependencies:
  - name: artifactory-ha
    version: 2.4.1
    repository: https://charts.jfrog.io/
  - name: xray
    version: 3.2.1
    repository: https://charts.jfrog.io/
  - name: distribution
    version: 5.1.0
    repository: https://charts.jfrog.io/
  - name: mission-control
    version: 3.1.1
    repository: https://charts.jfrog.io/
  - name: pipelines
    version: 1.1.0
    repository: https://charts.jfrog.io/
